apiVersion: daas.tenxcloud.com/v1
kind: FlinkCluster
metadata:
  name: flinksessioncluster-sample
spec:
  serviceAccountName: flink-sa
  image:
    name: 'xiaolin8/flink:1.14.4'
    pullPolicy: Always
  jobManager:
    accessScope: Cluster
    securityContext:
      runAsUser: 9999
      runAsGroup: 9999
    ports:
      ui: 8081
    resources:
      limits:
        memory: 1024Mi
        cpu: 200m
  taskManager:
    replicas: 1
    resources:
      limits:
        memory: 1024Mi
        cpu: 200m
    volumes:
      - name: cache-volume
        emptyDir: {}
    volumeMounts:
      - mountPath: /cache
        name: cache-volume
    sidecars:
      - name: sidecar
        image: 'xiaolin8/alpine:3.14-bash'
        command:
          - sleep
          - '10000'
  flinkProperties:
    taskmanager.numberOfTaskSlots: '1'
    taskmanager.memory.flink.size: "800MB"