apiVersion: v1
kind: Service
metadata:
  name: hadoop-yarn-resourcemanager
spec:
  type: NodePort
  selector:
    app: hadoop-yarn-resourcemanager
  ports:
    - name: "8030"
      port: 8030
    - name: "8031"
      port: 8031
    - name: "8032"
      port: 8032
    - name: http
      port: 8088
      targetPort: 8088
      nodePort: 32088
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hadoop-yarn-resourcemanager
  name: hadoop-yarn-resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-yarn-resourcemanager
  serviceName: hadoop-yarn-resourcemanager
  template:
    metadata:
      labels:
        app: hadoop-yarn-resourcemanager
    spec:
      containers:
        - args:
            - /bin/bash
            - /hdfs-scripts/bootstrap.sh
            - -d
          command:
            - /entrypoint.sh
          env:
            - name: HADOOP_CUSTOM_CONF_DIR
              value: /etc/hadoop-custom-conf
            - name: MULTIHOMED_NETWORK
              value: "0"
            - name: HADOOP_PREFIX
              value: /opt/hadoop-2.7.2
            - name: NODE_TYPE
              value: hdfs-rm
            - name: MY_POD
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: RESOUCEMANAGER_POD_0
              value: my-hdfs-yarn-master-0
          image: dev-registry.tenxcloud.com/system_containers/hadoop:uhopper_2.7.2
          imagePullPolicy: Always
          name: resourcemanager
          ports:
            - containerPort: 9000
            - containerPort: 50070
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /hdfs-scripts
              name: hdfs-scripts
            - mountPath: /etc/hadoop-custom-conf
              name: hdfs-config
              readOnly: true
      volumes:
        - configMap:
            defaultMode: 484
            name: my-hdfs-scripts
            optional: true
          name: hdfs-scripts
        - configMap:
            defaultMode: 420
            name: my-hdfs-config
            optional: true
          name: hdfs-config
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-yarn-nodemanager
spec:
  clusterIP: None
  selector:
    app: hadoop-yarn-nodemanager
  ports:
    - name: "8040"
      port: 8040
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hadoop-yarn-nodemanager
  name: hadoop-yarn-nodemanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hadoop-yarn-nodemanager
  serviceName: hadoop-yarn-nodemanager
  template:
    metadata:
      labels:
        app: hadoop-yarn-nodemanager
    spec:
      containers:
        - args:
            - /bin/bash
            - /hdfs-scripts/bootstrap.sh
            - -d
          command:
            - /entrypoint.sh
          env:
            - name: HADOOP_CUSTOM_CONF_DIR
              value: /etc/hadoop-custom-conf
            - name: MULTIHOMED_NETWORK
              value: "0"
            - name: HADOOP_PREFIX
              value: /opt/hadoop-2.7.2
            - name: NODE_TYPE
              value: hdfs-nm
            - name: MY_POD
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: RESOUCEMANAGER_POD_0
              value: my-hdfs-yarn-master-0
          image: dev-registry.tenxcloud.com/system_containers/hadoop:uhopper_2.7.2
          imagePullPolicy: Always
          name: nodemanager
          ports:
            - containerPort: 8040
            - containerPort: 8041
            - containerPort: 8042
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /hdfs-scripts
              name: hdfs-scripts
            - mountPath: /etc/hadoop-custom-conf
              name: hdfs-config
              readOnly: true
      volumes:
        - configMap:
            defaultMode: 484
            name: my-hdfs-scripts
            optional: true
          name: hdfs-scripts
        - configMap:
            defaultMode: 420
            name: my-hdfs-config
            optional: true
          name: hdfs-config